"""add checkout_request_id to payments

Revision ID: 67643be0a090
Revises: 48742bb8abe2
Create Date: 2026-07-18 17:47:57.671456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67643be0a090'
down_revision: Union[str, Sequence[str], None] = '48742bb8abe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('checkout_request_id', sa.String(), nullable=True), schema='pos')
    op.create_index(op.f('ix_pos_payments_checkout_request_id'), 'payments', ['checkout_request_id'], unique=False, schema='pos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pos_payments_checkout_request_id'), table_name='payments', schema='pos')
    op.drop_column('payments', 'checkout_request_id', schema='pos')
    # ### end Alembic commands ###
